//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "stocks_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub time: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub symbol: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub open: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub high: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub low: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub close: Option<f64>,
    pub volume: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
